# # version: '3.8'  # Optional: You can remove this line if it's causing issues.

# services:
#   backend:
#     build: ./flask-server
#     container_name: backend
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./flask-server:/app
#     depends_on:
#       - frontend

#   frontend:
#     build: ./client2
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./client2:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     stdin_open: true
#     tty: true
#     command: ["npm", "start"]


services:
  backend:
    build: ./flask-server
    container_name: flask_backend
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./client2
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client2:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: ["npm", "start"]
